"""
report_generator.py
-------------------
Generates downloadable analysis reports in Markdown and plain-text formats.
No external dependencies — uses only Python stdlib.
"""

from datetime import datetime
from typing import Dict, Any


# ---------------------------------------------------------------------------
# Markdown Report
# ---------------------------------------------------------------------------

def generate_markdown_report(result: Dict[str, Any], job_role: str, resume_filename: str = "") -> str:
    """
    Generate a rich Markdown report from the analysis result dict.

    Args:
        result (dict): Analysis result returned by ResumeAnalyzer.
        job_role (str): Target job role.
        resume_filename (str): Original resume filename.

    Returns:
        str: Complete Markdown report as a string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    filename_line = f"**Resume file:** `{resume_filename}`\n" if resume_filename else ""

    # Extract fields with safe defaults
    candidate    = result.get("candidate_name", "Not found")
    experience   = result.get("years_of_experience", "Unknown")
    overall      = result.get("overall_evaluation", "N/A")
    ats_score    = result.get("ats_score", 0)
    ats_explain  = result.get("ats_score_explanation", "")
    skills       = result.get("skills_detected", [])
    missing      = result.get("missing_skills", [])
    strengths    = result.get("strengths", [])
    improvements = result.get("suggested_improvements", [])
    keywords     = result.get("keywords_to_add", [])
    kw_tips      = result.get("keyword_optimization_tips", [])
    alt_titles   = result.get("recommended_job_titles", [])
    jd_score     = result.get("jd_match_score")
    jd_matched   = result.get("jd_matched_keywords", [])
    jd_missing   = result.get("jd_missing_keywords", [])
    breakdown    = result.get("ats_breakdown", {})
    section_fb   = result.get("section_feedback", {})

    # ATS score bar (ASCII)
    filled = int(ats_score / 5)
    bar = "█" * filled + "░" * (20 - filled)

    md = f"""# 📄 AI Resume Analysis Report

**Generated:** {now}
**Target Role:** {job_role}
{filename_line}
---

## 👤 Candidate Overview

| Field | Value |
|-------|-------|
| Name | {candidate} |
| Estimated Experience | {experience} |
| Target Job Role | {job_role} |

---

## 📝 Overall Evaluation

{overall}

---

## 🎯 ATS Compatibility Score

**Score: {ats_score}/100**

```
[{bar}] {ats_score}%
```

{ats_explain}
"""

    # ATS breakdown sub-scores
    if breakdown:
        md += "\n### ATS Sub-Score Breakdown\n\n"
        md += "| Category | Score | Max |\n|----------|-------|-----|\n"
        labels = {
            "keyword_match": "Keyword Match",
            "formatting": "Formatting",
            "section_completeness": "Section Completeness",
            "contact_info": "Contact Info",
        }
        for key, label in labels.items():
            val = breakdown.get(key, "—")
            md += f"| {label} | {val} | 25 |\n"
        md += "\n"

    md += "---\n\n"

    # JD Comparison (optional)
    if jd_score is not None:
        md += f"""## 📋 Job Description Match

**JD Match Score: {jd_score}/100**

### ✅ Keywords Found in Your Resume ({len(jd_matched)})

{', '.join(f'`{k}`' for k in jd_matched) or '_None_'}

### ❌ Missing JD Keywords ({len(jd_missing)})

{', '.join(f'`{k}`' for k in jd_missing) or '_None_'}

---

"""

    # Skills
    md += f"""## ✅ Skills Detected ({len(skills)})

{', '.join(f'`{s}`' for s in skills) or '_None detected_'}

---

## ❌ Missing Skills for {job_role} ({len(missing)})

{', '.join(f'`{s}`' for s in missing) or '_None — great match!_'}

---

"""

    # Strengths
    if strengths:
        md += "## 💪 Strengths\n\n"
        for s in strengths:
            md += f"- ✨ {s}\n"
        md += "\n---\n\n"

    # Section feedback
    if section_fb:
        md += "## 📂 Section-by-Section Feedback\n\n"
        for sec, tip in section_fb.items():
            md += f"**{sec.title()}:** {tip}\n\n"
        md += "---\n\n"

    # Improvements
    if improvements:
        md += "## 💡 Suggested Improvements\n\n"
        for i, imp in enumerate(improvements, 1):
            md += f"{i}. 🔧 {imp}\n"
        md += "\n---\n\n"

    # Keyword optimization
    if kw_tips:
        md += "## ✍️ Keyword Optimization Tips\n\n"
        for tip in kw_tips:
            md += f"- {tip}\n"
        md += "\n---\n\n"

    # Keywords to add
    if keywords:
        md += f"## 🔑 ATS Keywords to Add\n\n"
        md += ' '.join(f'`{k}`' for k in keywords) + "\n\n---\n\n"

    # Recommended titles
    if alt_titles:
        md += "## 🧭 Other Roles You May Fit\n\n"
        md += ', '.join(f'**{t}**' for t in alt_titles) + "\n\n---\n\n"

    md += "_Report generated by AI Resume Analyzer · Powered by LangChain & OpenAI_\n"
    return md


# ---------------------------------------------------------------------------
# Plain Text Report
# ---------------------------------------------------------------------------

def generate_txt_report(result: Dict[str, Any], job_role: str, resume_filename: str = "") -> str:
    """
    Generate a clean plain-text report from the analysis result dict.

    Args:
        result (dict): Analysis result returned by ResumeAnalyzer.
        job_role (str): Target job role.
        resume_filename (str): Original resume filename.

    Returns:
        str: Plain-text report as a string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    SEP = "=" * 60
    sep = "-" * 60

    def section(title):
        return f"\n{SEP}\n  {title.upper()}\n{SEP}\n"

    def bullet_list(items, prefix="•"):
        return "\n".join(f"  {prefix} {item}" for item in items) if items else "  None"

    candidate    = result.get("candidate_name", "Not found")
    experience   = result.get("years_of_experience", "Unknown")
    overall      = result.get("overall_evaluation", "N/A")
    ats_score    = result.get("ats_score", 0)
    ats_explain  = result.get("ats_score_explanation", "")
    skills       = result.get("skills_detected", [])
    missing      = result.get("missing_skills", [])
    strengths    = result.get("strengths", [])
    improvements = result.get("suggested_improvements", [])
    keywords     = result.get("keywords_to_add", [])
    kw_tips      = result.get("keyword_optimization_tips", [])
    alt_titles   = result.get("recommended_job_titles", [])
    jd_score     = result.get("jd_match_score")
    jd_matched   = result.get("jd_matched_keywords", [])
    jd_missing   = result.get("jd_missing_keywords", [])
    breakdown    = result.get("ats_breakdown", {})
    section_fb   = result.get("section_feedback", {})

    filled = int(ats_score / 5)
    bar = "█" * filled + "░" * (20 - filled)

    lines = [
        "AI RESUME ANALYSIS REPORT",
        f"Generated : {now}",
        f"Target Role: {job_role}",
    ]
    if resume_filename:
        lines.append(f"Resume File: {resume_filename}")

    lines += [
        "",
        section("Candidate Overview"),
        f"  Name           : {candidate}",
        f"  Experience     : {experience}",
        f"  Target Role    : {job_role}",

        section("Overall Evaluation"),
        f"  {overall}",

        section(f"ATS Score: {ats_score}/100"),
        f"  [{bar}] {ats_score}%",
        "",
        f"  {ats_explain}",
    ]

    if breakdown:
        lines += ["", "  Sub-Score Breakdown:", sep]
        labels = {
            "keyword_match": "Keyword Match",
            "formatting": "Formatting",
            "section_completeness": "Section Completeness",
            "contact_info": "Contact Info",
        }
        for key, label in labels.items():
            val = breakdown.get(key, "—")
            lines.append(f"  {label:<25}: {val}/25")

    if jd_score is not None:
        lines += [
            section(f"Job Description Match: {jd_score}/100"),
            f"  Matched Keywords ({len(jd_matched)}): {', '.join(jd_matched) or 'None'}",
            f"  Missing Keywords ({len(jd_missing)}): {', '.join(jd_missing) or 'None'}",
        ]

    lines += [
        section(f"Skills Detected ({len(skills)})"),
        bullet_list(skills),

        section(f"Missing Skills for {job_role}"),
        bullet_list(missing) if missing else "  None — great match!",
    ]

    if strengths:
        lines += [section("Strengths"), bullet_list(strengths, "✓")]

    if section_fb:
        lines.append(section("Section-by-Section Feedback"))
        for sec, tip in section_fb.items():
            lines.append(f"  [{sec.upper()}] {tip}")

    if improvements:
        lines.append(section("Suggested Improvements"))
        for i, imp in enumerate(improvements, 1):
            lines.append(f"  {i}. {imp}")

    if kw_tips:
        lines += [section("Keyword Optimization Tips"), bullet_list(kw_tips)]

    if keywords:
        lines += [section("ATS Keywords to Add"), f"  {', '.join(keywords)}"]

    if alt_titles:
        lines += [section("Other Roles You May Fit"), f"  {', '.join(alt_titles)}"]

    lines += ["", SEP, "Report generated by AI Resume Analyzer", SEP]

    return "\n".join(lines)
